#!/usr/bin/env bash

# environment
#
# Copyright 2020 Andrew Countryman <apcountryman@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
# file except in compliance with the License. You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# File: update
# Description: Update a host or VM.

function error()
{
    local -r message="$1"

    ( >&2 echo "$mnemonic: $message" )
}

function abort()
{
    if [[ "$#" -gt 0 ]]; then
        local -r message="$1"

        error "$message, aborting"
    fi

    exit 1
}

function display_help_text()
{
    echo "NAME"
    echo "    $mnemonic - Update a host or VM."
    echo "SYNOPSIS"
    echo "    $mnemonic --help"
    echo "    $mnemonic --version"
    echo "    $mnemonic --environment <type>"
    echo "OPTIONS"
    echo "    --environment <type>"
    echo "        Specify the type of environment that is being updated. The following"
    echo "        environment types are supported:"
    echo "            host"
    echo "            vm"
    echo "    --help"
    echo "        Display this help text."
    echo "    --version"
    echo "        Display the version of this script."
    echo "EXAMPLES"
    echo "    $mnemonic --help"
    echo "    $mnemonic --version"
    echo "    $mnemonic --environment host"
    echo "    $mnemonic --environment vm"
}

function display_version()
{
    echo "$mnemonic, version $version"
}

function ensure_environment_has_been_configured()
{
    if [[ ! -e "$log_file" ]]; then
        abort "environment has not been configured"
    fi
}

function log_event()
{
    local -r event="$1"

    if ! echo "$( date --utc +'%F %H:%M:%S' ) ($version) - $event" | sudo tee -a "$log_file"; then
        abort "log failure"
    fi
}

function update_environment()
{
    local -r log_file="/var/log/environment"

    ensure_environment_has_been_configured

    log_event "update started"

    log_event "update completed"
}

function main()
{
    local -r script=$( readlink -f "$0" )
    local -r mnemonic=$( basename "$script" )
    local -r repository=$( dirname "$script" )
    local -r version=$( git -C "$repository" describe --always --dirty --broken )

    while [[ "$#" -gt 0 ]]; do
        local argument="$1"; shift

        case "$argument" in
            --help)
                display_help_text
                exit
                ;;
            --version)
                display_version
                exit
                ;;
            --environment)
                if [[ -n "$environment" ]]; then
                    abort "environment type already specified"
                fi

                if [[ "$#" -le 0 ]]; then
                    abort "environment type not specified"
                fi

                local -r environment="$1"; shift

                if [[ "$environment" != "host" && "$environment" != "vm" ]]; then
                    abort "'$environment' is not a supported environment type"
                fi
                ;;
            --*)
                ;&
            -*)
                abort "'$argument' is not a supported option"
                ;;
            *)
                abort "'$argument' is not a valid argument"
                ;;
        esac
    done

    if [[ -z "$environment" ]]; then
        abort "'--environment' must be specified"
    fi

    update_environment
}

main "$@"
